// <auto-generated />
using System;
using CajeroAutomaticoAPI.Data.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CajeroAutomaticoAPI.Migrations
{
    [DbContext(typeof(CajeroAutomaticoDbContext))]
    partial class CajeroAutomaticoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CajeroAutomaticoAPI.Data.Models.LastOperation", b =>
                {
                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CantidadRetirada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Tarjeta")
                        .HasColumnType("int");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView("LastOperationView", (string)null);
                });

            modelBuilder.Entity("CajeroAutomaticoAPI.Data.Models.Operacion", b =>
                {
                    b.Property<int>("ID_Operacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Operacion"));

                    b.Property<decimal>("CantidadRetirada")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CodigoOperacion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Tarjeta")
                        .HasColumnType("int");

                    b.HasKey("ID_Operacion");

                    b.ToTable("Operaciones", (string)null);
                });

            modelBuilder.Entity("CajeroAutomaticoAPI.Data.Models.Tarjeta", b =>
                {
                    b.Property<int>("ID_Tarjeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Tarjeta"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("Bloqueada")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<int>("Intentos")
                        .HasColumnType("int");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<int>("PIN")
                        .HasColumnType("int");

                    b.HasKey("ID_Tarjeta");

                    b.ToTable("Tarjetas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
